"""empty message

Revision ID: 3504c148af7b
Revises: 66c2a333ae12
Create Date: 2021-10-27 12:03:19.130849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3504c148af7b'
down_revision = '66c2a333ae12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'date')
    # ### end Alembic commands ###
