"""empty message

Revision ID: 66c2a333ae12
Revises: 
Create Date: 2021-10-24 06:36:54.680817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c2a333ae12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('stock_code', sa.String(length=8), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'stock_code')
    )
    op.create_index(op.f('ix_stocks_stock_code'), 'stocks', ['stock_code'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('alert_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_index(op.f('ix_stocks_stock_code'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
