"""init

Revision ID: 84e99fbbb71b
Revises: 
Create Date: 2021-10-23 08:31:29.815729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e99fbbb71b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('stock_code', sa.String(length=8), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_stock_code'), 'stock', ['stock_code'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('alert_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',

    )
    op.drop_table('alerts')
    op.drop_index(op.f('ix_stock_stock_code'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
