"""empty message

Revision ID: d90b9971beb2
Revises: 3504c148af7b
Create Date: 2021-10-29 11:53:54.842154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90b9971beb2'
down_revision = '3504c148af7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
