"""empty message

Revision ID: e9e4e8d61c78
Revises: d90b9971beb2
Create Date: 2021-10-30 07:17:29.899556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e4e8d61c78'
down_revision = 'd90b9971beb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('company_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'company_name')
    # ### end Alembic commands ###
